### ISSUE TITLE
What about ola.sql script?

### ISSUE THREAD

**Issue by ktaranov** [DC-AC/SQL2016_Scripted_Install#7]

**Comment by jdanton** [comment]
I am not clear as to what you mean--the first step in the PowerShell is to do an invoke-webrequest to gets Ola's latest code and then after SQL is installed, to run it. Are you having an issue? If you server does not have internet access this would fail.

**Comment by ktaranov** [comment]
Sorry for this issue, closed. I get error `invoke-WebRequest : Не удалось найти часть пути "C:\temp\ola.sql".`, and solve it - change on another disk and remove temp folder.
